"""Shared plumbing for the Unit 6 evidence scripts.

`unit6_integration.py` proves the assembled system works end to end;
`unit6_perf.py` measures it. Both need the same three things — a hermetic
throwaway database, a real ``uvicorn`` process, and the derived field-week
laboratory export — so they live here once rather than being copy-pasted and
drifting apart.

The important property is that a run is *hermetic*. Every script points
``AQUAOPS_DB_URL`` at a fresh temporary SQLite file and
``AQUAOPS_EVIDENCE_DIR`` at a temporary directory, so re-running produces the
same transcript from a clean clone instead of accumulating state, and a
measurement can never be an artefact of a previous run.

    from examples.unit6_harness import live_server, field_week_csv
"""

from __future__ import annotations

import contextlib
import csv
import io
import os
import socket
import subprocess
import sys
import tempfile
import time
from collections.abc import Iterator
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

import httpx

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT.parent / "Unit6" / "evidence"

CHLORINE_CSV = ROOT / "data" / "networks" / "maple_creek_chlorine_48h.csv"
POINTS_CSV = ROOT / "data" / "networks" / "maple_creek_points.csv"
DEMO_CSV = ROOT / "examples" / "demo_lab_results.csv"

#: The WNTR simulation needs eight hours of hydraulic warm-up; every node reads
#: 0.0 mg/L until the solver settles. Ingesting or scoring that would be
#: measuring the solver, not the water, so it is dropped.
WARMUP_READINGS = 8

#: The simulated series carries an elapsed-time index, not a calendar date.
#: Anchoring it to the Monday of ISO week 38 puts the readings inside a week the
#: rule engine can actually schedule.
FIELD_WEEK_START = datetime(2026, 9, 14, 0, 0, 0)
ISO_WEEK = "2026-W38"

#: The six dead-end spurs in the committed registry — the geometry where the
#: Unit 5 work found chlorine decaying fastest.
DEAD_END_POINTS = ("SP07", "SP11", "SP12", "SP13", "SP15", "SP18")

#: Endpoints measured by `unit6_perf.py`. Declared here so the integration and
#: performance transcripts cannot disagree about what "the API" is.
BENCHMARK_ENDPOINTS: tuple[tuple[str, str], ...] = (
    ("GET", "/health"),
    ("GET", "/api/v1/systems/maple-creek"),
    ("GET", "/api/v1/systems/maple-creek/sampling-points"),
    ("GET", "/api/v1/readings?point=SP15&limit=500"),
    ("GET", "/api/v1/alerts"),
    ("GET", "/api/v1/rules"),
    ("GET", "/api/v1/tasks?week=2026-W38"),
    ("GET", "/dash/network"),
    ("GET", "/dash/week?week=2026-W38"),
    ("GET", "/"),
)


@dataclass
class LiveServer:
    """A running instance of the deployable unit, plus how to reach it."""

    base_url: str
    port: int
    scratch: Path
    process: subprocess.Popen[bytes]
    #: Everything the child wrote, filled in once it has been terminated. The
    #: pipe is deliberately drained *after* shutdown: reading it while the
    #: process is still alive blocks until the child exits, which would deadlock
    #: any script that tried to collect server output from a `finally` block.
    output: str = ""

    def peak_rss_kb(self) -> float | None:
        """Peak resident set size of the server, in KiB.

        Only meaningful once the process has been reaped, because the operating
        system reports a child's usage to `getrusage(RUSAGE_CHILDREN)` when it is
        waited for. Call it after the `live_server` context has exited.
        """
        return peak_child_rss_kb()


def free_port() -> int:
    """Ask the kernel for an unused loopback port."""
    with socket.socket() as probe:
        probe.bind(("127.0.0.1", 0))
        return int(probe.getsockname()[1])


def field_week_csv() -> bytes:
    """Derive a field-week laboratory export from the committed simulation.

    Nothing here is invented. The numbers come from
    ``data/networks/maple_creek_chlorine_48h.csv`` — the 48-hour WNTR ground
    truth generated by ``examples/build_maple_creek.py`` — and only two
    transformations are applied, both documented in the Unit 6 report: the
    eight-hour hydraulic warm-up is dropped, and the elapsed-time index is
    anchored to a real calendar week so the readings fall inside an ISO week the
    rule engine can schedule.
    """
    with CHLORINE_CSV.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))[WARMUP_READINGS:]

    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow(["sampling_point_id", "measured_at", "free_chlorine_mg_l"])
    for offset, row in enumerate(rows):
        measured_at = FIELD_WEEK_START + timedelta(hours=offset)
        for point_id in DEAD_END_POINTS:
            writer.writerow(
                [
                    point_id,
                    measured_at.strftime("%Y-%m-%dT%H:%M:%SZ"),
                    round(float(row[point_id]), 4),
                ]
            )
    return buffer.getvalue().encode()


def wait_for_health(
    base_url: str, process: subprocess.Popen[bytes], timeout: float = 90.0
) -> tuple[dict[str, Any], int]:
    """Poll ``/health`` until the app answers; return the payload and boot ms."""
    started = time.monotonic()
    deadline = started + timeout
    last_error = "no attempt made"
    while time.monotonic() < deadline:
        if process.poll() is not None:
            raise SystemExit(
                f"uvicorn exited with code {process.returncode} before becoming healthy"
            )
        try:
            response = httpx.get(f"{base_url}/health", timeout=2.0)
            if response.status_code == 200:
                return response.json(), int((time.monotonic() - started) * 1000)
        except httpx.HTTPError as error:  # not listening yet
            last_error = type(error).__name__
        time.sleep(0.2)
    raise SystemExit(f"server never became healthy ({last_error})")


@contextlib.contextmanager
def live_server(
    *, extra_env: dict[str, str] | None = None, port: int | None = None
) -> Iterator[LiveServer]:
    """Boot the deployable unit in a throwaway environment.

    Yields a :class:`LiveServer`. The child keeps its own database, evidence
    directory and Matplotlib cache inside a temporary directory, and is always
    torn down, so a script that crashes still releases the port.
    """
    with tempfile.TemporaryDirectory(prefix="aquaops-u6-") as scratch:
        scratch_path = Path(scratch)
        env = {
            **os.environ,
            "AQUAOPS_DB_URL": f"sqlite:///{scratch_path / 'runtime.db'}",
            "AQUAOPS_EVIDENCE_DIR": str(scratch_path / "eval"),
            "MPLCONFIGDIR": str(scratch_path / "mpl"),
            **(extra_env or {}),
        }
        chosen = port or free_port()
        server = subprocess.Popen(
            [
                sys.executable,
                "-m",
                "uvicorn",
                "app.main:app",
                "--host",
                "127.0.0.1",
                "--port",
                str(chosen),
                "--log-level",
                "warning",
            ],
            cwd=ROOT,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        live = LiveServer(
            base_url=f"http://127.0.0.1:{chosen}",
            port=chosen,
            scratch=scratch_path,
            process=server,
        )
        try:
            yield live
        finally:
            server.terminate()
            try:
                server.wait(timeout=15)
            except subprocess.TimeoutExpired:
                server.kill()
                server.wait(timeout=5)
            live.output = server_output(server)


def server_output(server: subprocess.Popen[bytes]) -> str:
    """Whatever the child wrote, read once after it has exited."""
    if server.stdout is None:
        return ""
    try:
        return server.stdout.read().decode(errors="replace").strip()
    except ValueError:  # stream already consumed
        return ""


def _normalise_maxrss(raw: float) -> float:
    """`ru_maxrss` is bytes on macOS and KiB on Linux; report KiB everywhere."""
    return raw / 1024.0 if sys.platform == "darwin" else float(raw)


def peak_child_rss_kb() -> float | None:
    """Peak resident set size of child processes reaped so far, in KiB.

    The process table is not readable from this sandbox and ``psutil`` is not a
    project dependency, but the interpreter's own ``resource`` module reports a
    reaped child's peak resident size without either. It is a *peak*, not a
    snapshot, which is the more useful figure for sizing hardware: it is the
    worst case the service actually reached.
    """
    try:
        import resource
    except ImportError:  # pragma: no cover - not reachable on macOS or Linux
        return None
    try:
        return round(_normalise_maxrss(resource.getrusage(resource.RUSAGE_CHILDREN).ru_maxrss), 1)
    except (OSError, ValueError):  # pragma: no cover - platform dependent
        return None


def interpreter_rss_kb(imports: str = "") -> float | None:
    """Peak RSS of a fresh interpreter after importing ``imports``, in KiB.

    This is how the memory cost of each layer of the stack is separated: a bare
    interpreter, then the application's own import surface, then the offline
    simulation stack. The difference between the last two is the argument for a
    slimmer production image, and it is measured rather than asserted.
    """
    code = (
        "import resource, sys\n"
        + (f"import {imports}\n" if imports else "")
        + "u = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss\n"
        + "print(u / 1024.0 if sys.platform == 'darwin' else u)\n"
    )
    try:
        completed = subprocess.run(
            [sys.executable, "-c", code],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
            timeout=180,
            env={**os.environ, "MPLCONFIGDIR": os.environ.get("MPLCONFIGDIR", "/tmp/mplcache")},
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if completed.returncode != 0:
        return None
    try:
        return round(float(completed.stdout.strip()), 1)
    except ValueError:
        return None


def git_sha() -> str:
    """The commit the measurement was produced from, as the design requires."""
    completed = subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    sha = completed.stdout.strip()
    return sha or "unknown"


def seed_case(client: httpx.Client) -> dict[str, Any]:
    """Put the case system into a demonstrable state over HTTP.

    Shared by the performance and usability scripts so both evaluate the same
    system: the committed demonstration export, the field week derived from the
    WTR ground truth, a detection pass over every dead-end spur, the week's
    duties, and a plan.
    """
    facts: dict[str, Any] = {}
    for filename, payload in (
        ("demo_lab_results.csv", DEMO_CSV.read_bytes()),
        ("field_week_2026-W38.csv", field_week_csv()),
    ):
        receipt = client.post(
            "/api/v1/systems/maple-creek/ingest/lab-csv",
            files={"file": (filename, payload, "text/csv")},
        ).json()
        facts[f"ingest_{filename}"] = receipt

    for point_id in DEAD_END_POINTS:
        client.post("/api/v1/detect/run", params={"point": point_id})

    tasks = client.post("/api/v1/tasks/generate", params={"week": ISO_WEEK}).json()
    facts["tasks_generated"] = tasks["generated"]

    plan = client.post(
        "/api/v1/plans", params={"week": ISO_WEEK, "solver": "greedy2opt"}
    ).json()
    facts["plan"] = {
        "stops": len(plan["stops"]),
        "total_km": plan["total_km"],
        "solver_ms": plan["solver_ms"],
    }
    facts["alerts_open"] = len(client.get("/api/v1/alerts").json())
    facts["readings_sp15"] = len(
        client.get("/api/v1/readings", params={"point": "SP15", "limit": 500}).json()
    )
    return facts


#: Chrome is used rather than a bundled headless-browser dependency because it
#: is already present on the developer's machine and the screenshot is evidence,
#: not a test fixture. Override with AQUAOPS_CHROME on another platform.
CHROME_CANDIDATES = (
    os.environ.get("AQUAOPS_CHROME", ""),
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/Applications/Chromium.app/Contents/MacOS/Chromium",
    "/usr/bin/google-chrome",
    "/usr/bin/chromium",
    "/usr/bin/chromium-browser",
)


def find_chrome() -> str | None:
    for candidate in CHROME_CANDIDATES:
        if candidate and Path(candidate).is_file():
            return candidate
    return None


def chrome_screenshot(
    url: str,
    out_path: Path,
    *,
    width: int = 1440,
    height: int = 1000,
    scale: float = 1.0,
    timeout: float = 60.0,
) -> bool:
    """Render a URL to a PNG with headless Chrome.

    Chrome does not reliably exit after writing a screenshot, so the process is
    polled and then terminated rather than waited on. The success signal is the
    file itself: non-empty on disk means the capture completed.
    """
    browser = find_chrome()
    if browser is None:
        return False
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.unlink(missing_ok=True)

    with tempfile.TemporaryDirectory(prefix="aquaops-shot-") as profile:
        process = subprocess.Popen(
            [
                browser,
                "--headless=new",
                "--disable-gpu",
                "--no-sandbox",
                "--hide-scrollbars",
                "--no-first-run",
                "--no-default-browser-check",
                "--disable-extensions",
                "--disable-background-networking",
                "--disable-sync",
                "--mute-audio",
                f"--user-data-dir={profile}",
                f"--crash-dumps-dir={profile}",
                f"--force-device-scale-factor={scale}",
                f"--window-size={width},{height}",
                "--virtual-time-budget=4000",
                f"--screenshot={out_path}",
                url,
            ],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        deadline = time.monotonic() + timeout
        try:
            while time.monotonic() < deadline:
                if out_path.exists() and out_path.stat().st_size > 0:
                    time.sleep(0.4)  # let Chrome finish flushing the PNG
                    return True
                if process.poll() is not None:
                    return out_path.exists() and out_path.stat().st_size > 0
                time.sleep(0.25)
            return False
        finally:
            process.terminate()
            try:
                process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait(timeout=5)
